# Site settings
title: 'Andrea Peretti'
email: peretti.and@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Portfolio di uno studente della laurea magistrale in <strong>Realtà Virtuale e Multimedialità</strong> 
  presso il <strong>Dipartimento di Informatica</strong> dell&rsquo;<strong>Universit&agrave; degli Studi di Torino</strong>.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.andxet.com" # the base hostname & protocol for your site
twitter_username: andxet
github_username:  andxet

# Build settings
markdown: kramdown
sass:
    style: :compressed